### ISSUE TITLE
Build process shows errors

### ISSUE THREAD

**Issue by DaveBitter** [mirabeau-nl/frontend-boilerplate#105]
Currently, the build process shows errors. This is with a fresh clone and install.

```
errorify: Error: Cannot find module 'core-js/es6/promise' from '/Users/dbitter/Documents/code/frontend-boilerplate/src/static/js'
errorify: Error: Cannot find module 'core-js/es6/symbol' from '/Users/dbitter/Documents/code/frontend-boilerplate/src/static/js'
errorify: Error: Cannot find module 'core-js/fn/dom-collections/iterator' from '/Users/dbitter/Documents/code/frontend-boilerplate/src/static/js'
errorify: Error: Cannot find module 'core-js/fn/array/from' from '/Users/dbitter/Documents/code/frontend-boilerplate/src/static/js'
errorify: Error: Cannot find module 'core-js/fn/object/assign' from '/Users/dbitter/Documents/code/frontend-boilerplate/src/static/js'
```

Installing core-js manually, `yarn add core-js` doesn't resolve the error. I suspect that the package got updated and the paths are changed.

**Comment by wolfpilot** [comment]
You'll need to install **v2.6.5** specifically, you most likely got **v3.x.x** which does indeed use new exports. It would be a good idea to lock all of the existing dependency versions anyway, but for now this should do.

`yarn add core-js@2.6.5` or `npm install --save core-js@2.6.5`

**Comment by wolfpilot** [comment]
Did this solve your issue, @DaveBitter ?

**Comment by DaveBitter** [comment]
I just made a fresh install and this issue was no longer happening. Closing it.
