### ISSUE TITLE
Babel error when installing fresh repository with yarn

### ISSUE THREAD

**Issue by DaveBitter** [mirabeau-nl/frontend-boilerplate#115]
**Describe the bug**
The `gulp dev` command throws an error and will not run when you do a fresh install of the boilerplate and continue to install the node_modules with `yarn install`.

The error being thrown: 
`yarn run v1.13.0`
`$ gulp dev`
`[18:22:22] Failed to load external module @babel/register`
`[18:22:22] Failed to load external module babel-register`
`[18:22:22] Failed to load external module babel-core/register`
`[18:22:22] Failed to load external module babel/register`
`[18:22:22] Local gulp not found in ~/Downloads/foo`
`[18:22:22] Try running: npm install gulp`
`error Command failed with exit code 1.`
`info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

I was able to fix the issue by installing the node_modules with `npm install`, but it should support Yarn in my opinion.

**To Reproduce**
Steps to reproduce the behaviour:
1. Do a fresh clone of the boilerplate
2. Run `yarn install`
3. Run `yarn dev`
4. Error throws. Now run `npm install` followed by `yarn dev` and it will work.

**Expected behaviour**
It should not throw an error if you installed the node_modules with Yarn.

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS: macOS 
 - 10.14.2 (18C54)

**Comment by Thomas-Machielsen** [comment]
Can't reproduce, seems to work fine. 
Can you try to reproduce this @DaveBitter?

**Comment by Hirbod** [comment]
I also can't reproduce this. Yarn is working out of the box

**Comment by DaveBitter** [comment]
I can't reproduce this issue anymore. I will close it 👍
