### ISSUE TITLE
Webpack / Rollup Version

### ISSUE THREAD

**Issue by hirbod** [mirabeau-nl/frontend-boilerplate#129]
Hi,

do you guys have a webpack/rollup version of this boilerplate laying around somewhere?
I think this setup with browserify got a bit outdated and now I've been working with it quite a while, compiling time is terrible due to missing HMR, and its so slow on bigger websites and it lacks of good tree shaking (even with extra browserify plugins).

The most lovely part of this template is the documentation generation, thats the only thing that actually keeps me here.
Was hoping you guys might have something ready in your pocket :)

**Comment by colin-aarts** [comment]
Hi @Hirbod, thanks for reaching out. Switching to Webpack is something I've been thinking about because of the reasons you mentioned (and also because it would make working with partial React codebases easier). While I can't promise anything, I'll definitely discuss it with the team :)

**Comment by Hirbod** [comment]
That would be lovely. I'm here if you need a beta tester
