### ISSUE TITLE
investigate .gitattributes file usages

### ISSUE THREAD

**Issue by awolkers** [mirabeau-nl/frontend-boilerplate#4]
During research I noticed that a lot of repo's contain a .gitattributes file.
This has something to do with line endings of files. Do we need this in our project?

https://help.github.com/articles/dealing-with-line-endings/

**Comment by sanjaytwisk** [comment]
Does anyone have a usecase?

**Comment by colin-aarts** [comment]
No use case provided, no longer relevant. Closing.
