### ISSUE TITLE
Code changes trigger browserifies watchify multiple times

### ISSUE THREAD

**Issue by peeke** [mirabeau-nl/frontend-boilerplate#93]
Javascript changes sometimes trigger watchify multiple times, depending on which bundle the changes happen in:

- Changes in the first bundle trigger watchify once
- Changes in the second bundle trigger watchify twice
- Changes in the third bundle trigger watchify three times
- And so on...

Which bundle triggers how many changes seems to depend on the order in which glob in the following code (tasks/js.js) returns the bundles:

```
gulp.task('js-browserify', done => {
  glob(config.js.src.bundles, (err, files) => {
    if (err) done(err)

    const tasks = files
      .map(bundleFile)
      .map(bundler => new Promise(resolve => bundler.on('end', resolve)))

    Promise.all(tasks).then(done)
  })
})
```

**Comment by wolfpilot** [comment]
Issue resolved in PR #94
