### ISSUE TITLE
Fatal error: "JavaScript heap out of memory" on css-lint task

### ISSUE THREAD

**Issue by rjsibon** [mirabeau-nl/frontend-boilerplate#96]
**Issue**

There is an issue with `stylelint-scss` that causes a fatal error: "JavaScript heap out of memory".
Similar to [this issue](https://github.com/kristerkari/stylelint-scss/issues/266#issuecomment-449971307).

**Fix**

Update stylelint-scss to v3.4.4.

**Comment by DaveBitter** [comment]
I could not reproduce this using the latest boilerplate. Does it always crash for you or do you have steps to reproduce?
